- name: use variable file
  hosts: all
  vars_files: 
      - ./var.txt
  tasks:
    - name: your fevourite pokemon
      debug:
        msg: "{{pokemon}}"    
    - name: print HI
      debug:
        msg: "{{pokemon}}"
    - name: local varible available
      debug:
        msg: "{{pokemon}}"
      vars:                     
        pokemon: "pichu"