- name: My first play
  hosts: all
  vars_files:
    - ./var.txt
  vars:
    pokemon: "pikachu"
  tasks:   
    - name: print hello msg
      debug:
        msg: "{{pokemon}}"

    - name: Print message
      debug:
       msg: "{{pokemon}}"