- name: change in blockinfile
  hosts: all
  tasks:
    - name: block adding
      blockinfile:
          path: /var/www/html/index.html
          marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
          block: |
              <h1> this is pune </h1>
              <h2> i am anil pawar </h1>
              <h3> this is mentore solution </h3>
    - name: restart apache2
      systemd:
         name: apache2     
         state: restarted