- name: My first play
  hosts: all
  vars:
     pokemon: "pikachu"
  tasks:   
    - name: print hello msg
      debug:
        msg: "{{pokemon}}"

    - name: Print message
      debug:
       msg: "{{pokemon}}"