- name: My first play
  hosts: all
  vars:
     pokeman: "pikachu"
  tasts:   
    - name: print hello msg
      debug:
        msg: "{{pokeman}}"

    - name: Print message
      debug:
       msg: "{{pokeman}}"