- name: yum and apt with conditions
  hosts: all
  tasks:
     - name: install httpd
       dnf:
         name: httpd
         state: latest
       when: ansible_os_family == "redhat" 
       ignore_errors: true
     - name: install apache2
       apt: 
         name: apache2
         state: latest
       when: ansible_os_family == "Debian"  