- name: change line in the existing file
  hosts: all
  tasks:
     - name: changing line
       lineinfile:
        path: /var/www/html/index.html
        regexp: '^h1'
        line: <h1> add lineinfile in copy module </h1>
     - name: restart apache2
       systemd:
        name: apache2
        state: restarted           